In [1]:
import numpy as np

In [2]:
ar1=np.array(6)

In [3]:
ar1

array(6)

In [4]:
type(ar1)

numpy.ndarray

In [5]:
ar2=np.array([2,3,4,5])

In [6]:
ar2

array([2, 3, 4, 5])

In [7]:
ar3=np.array([[2,3,4,5],[1,0,1,0]])

In [8]:
ar3

array([[2, 3, 4, 5],
       [1, 0, 1, 0]])

# Array types

1. Zero array
2. Ones array
3. empty array
4. array for range

# 1. Zero Array

In [9]:
zero_array=np.zeros(2)

In [10]:
zero_array

array([0., 0.])

In [11]:
zero_array=np.zeros((2,2))

In [12]:
zero_array

array([[0., 0.],
       [0., 0.]])

# 2.Ones Array

In [13]:
ones_array=np.ones((2,2))

In [14]:
ones_array

array([[1., 1.],
       [1., 1.]])

# 3.Arange

In [15]:
ar4=np.arange(2,15,2)

In [16]:
ar4

array([ 2,  4,  6,  8, 10, 12, 14])

# Transpose

In [17]:
ar5=np.transpose(ar3)

In [18]:
ar5

array([[2, 1],
       [3, 0],
       [4, 1],
       [5, 0]])

Single Row Transpose

In [19]:
ar6=np.ravel(ar5)

In [20]:
ar6

array([2, 1, 3, 0, 4, 1, 5, 0])

# Concatenation

In [21]:
a1=np.array([1,2])
a2=np.array([4,5])

In [22]:
a1

array([1, 2])

In [23]:
a2

array([4, 5])

In [24]:
concat=np.concatenate((a1,a2))

In [25]:
concat

array([1, 2, 4, 5])

horizantal concate

In [26]:
hori=np.hstack((a1,a2))

In [27]:
hori

array([1, 2, 4, 5])

 vertical concate

In [28]:
vert=np.vstack((a1,a2))

In [29]:
vert

array([[1, 2],
       [4, 5]])

# Determinants

In [30]:
mat1=np.array([[1,2,3],[4,5,6],[2,8,9]])

In [31]:
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [2, 8, 9]])

In [32]:
det_cf_mat1=np.linalg.det(mat1)

In [33]:
det_cf_mat1

15.000000000000007

# Inverse

In [34]:
inverse=np.linalg.inv(mat1)

In [35]:
inverse

array([[-0.2       ,  0.4       , -0.2       ],
       [-1.6       ,  0.2       ,  0.4       ],
       [ 1.46666667, -0.26666667, -0.2       ]])

# Dense

In [36]:
dense=np.array([[1,0,3,0],[0,0,0,6],[0,5,6,7],[0,0,1,1]])

In [37]:
dense

array([[1, 0, 3, 0],
       [0, 0, 0, 6],
       [0, 5, 6, 7],
       [0, 0, 1, 1]])

# Sparse

In [38]:
from scipy.sparse import csr_matrix

In [39]:
sparse=csr_matrix(dense)

In [40]:
sparse

<4x4 sparse matrix of type '<class 'numpy.intc'>'
	with 8 stored elements in Compressed Sparse Row format>

In [41]:
print(sparse)

  (0, 0)	1
  (0, 2)	3
  (1, 3)	6
  (2, 1)	5
  (2, 2)	6
  (2, 3)	7
  (3, 2)	1
  (3, 3)	1


In [48]:
ar=np.array([[1,2],[3,0]])

In [49]:
sparse=csr_matrix(ar)

In [50]:
sparse

<2x2 sparse matrix of type '<class 'numpy.intc'>'
	with 3 stored elements in Compressed Sparse Row format>