# MACHINE LEARNING-Supervised Learning

* Regression
* Classification

# SIMPLE LINEAR REGRESSION

# Importing Libraries

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt
%matplotlib inline

# Importing Data Set

In [4]:
my_data=pd.read_csv("Admission_Predict.csv")

In [5]:
my_data

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

    Research  Chance of Admit   
0        Yes              0.92  
1        Yes              0.76  
2        Yes              0.72  
3        Yes              0.80  
4         No              0.65  
..       ...               ...  
395      Yes              0.82  
396      Yes              0.84  
397      Yes              0.91  
398       No              0.67  
399      Yes              0.95  

[400 rows x 9 columns]

In [6]:
my_data2=my_data.drop(['Serial No.','GRE Score','TOEFL Score','University Rating','SOP','LOR ','Research'],axis=1)

In [7]:
my_data2

CGPA  Chance of Admit 
0    9.65              0.92
1    8.87              0.76
2    8.00              0.72
3    8.67              0.80
4    8.21              0.65
..    ...               ...
395  9.04              0.82
396  9.11              0.84
397  9.45              0.91
398  8.78              0.67
399  9.66              0.95

[400 rows x 2 columns]

In [8]:
x=my_data2.iloc[:,0].values.reshape(-1,1)

In [9]:
x

array([[9.65],
       [8.87],
       [8.  ],
       [8.67],
       [8.21],
       [9.34],
       [8.2 ],
       [7.9 ],
       [8.  ],
       [8.6 ],
       [8.4 ],
       [9.  ],
       [9.1 ],
       [8.  ],
       [8.2 ],
       [8.3 ],
       [8.7 ],
       [8.  ],
       [8.8 ],
       [8.5 ],
       [7.9 ],
       [8.4 ],
       [9.5 ],
       [9.7 ],
       [9.8 ],
       [9.6 ],
       [8.8 ],
       [7.5 ],
       [7.2 ],
       [7.3 ],
       [8.1 ],
       [8.3 ],
       [9.4 ],
       [9.6 ],
       [9.8 ],
       [9.2 ],
       [8.4 ],
       [7.8 ],
       [7.5 ],
       [7.7 ],
       [8.  ],
       [8.2 ],
       [8.5 ],
       [9.1 ],
       [9.4 ],
       [9.1 ],
       [9.3 ],
       [9.7 ],
       [8.85],
       [8.4 ],
       [8.3 ],
       [7.9 ],
       [8.  ],
       [8.1 ],
       [8.  ],
       [7.7 ],
       [7.4 ],
       [7.6 ],
       [6.8 ],
       [8.3 ],
       [8.1 ],
       [8.2 ],
       [8.2 ],
       [8.5 ],
       [8.7 ],
       [8.92],
       [9.

In [10]:
y=my_data2.iloc[:,1].values.reshape(-1,1)

In [11]:
y

array([[0.92],
       [0.76],
       [0.72],
       [0.8 ],
       [0.65],
       [0.9 ],
       [0.75],
       [0.68],
       [0.5 ],
       [0.45],
       [0.52],
       [0.84],
       [0.78],
       [0.62],
       [0.61],
       [0.54],
       [0.66],
       [0.65],
       [0.63],
       [0.62],
       [0.64],
       [0.7 ],
       [0.94],
       [0.95],
       [0.97],
       [0.94],
       [0.76],
       [0.44],
       [0.46],
       [0.54],
       [0.65],
       [0.74],
       [0.91],
       [0.9 ],
       [0.94],
       [0.88],
       [0.64],
       [0.58],
       [0.52],
       [0.48],
       [0.46],
       [0.49],
       [0.53],
       [0.87],
       [0.91],
       [0.88],
       [0.86],
       [0.89],
       [0.82],
       [0.78],
       [0.76],
       [0.56],
       [0.78],
       [0.72],
       [0.7 ],
       [0.64],
       [0.64],
       [0.46],
       [0.36],
       [0.42],
       [0.48],
       [0.47],
       [0.54],
       [0.56],
       [0.52],
       [0.55],
       [0.

# Splitting the dataset

In [12]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [15]:
x_train

array([[8.79],
       [8.7 ],
       [7.7 ],
       [9.18],
       [8.  ],
       [9.01],
       [8.36],
       [8.54],
       [9.04],
       [9.14],
       [8.84],
       [9.68],
       [7.4 ],
       [8.  ],
       [9.16],
       [8.48],
       [8.77],
       [8.24],
       [8.76],
       [8.9 ],
       [8.57],
       [8.5 ],
       [9.  ],
       [7.9 ],
       [8.9 ],
       [8.46],
       [9.5 ],
       [8.04],
       [8.75],
       [8.57],
       [8.  ],
       [8.76],
       [8.67],
       [8.4 ],
       [9.17],
       [9.26],
       [9.34],
       [8.4 ],
       [8.37],
       [8.13],
       [8.03],
       [8.45],
       [9.31],
       [8.27],
       [7.56],
       [9.44],
       [9.5 ],
       [8.54],
       [8.27],
       [7.8 ],
       [9.43],
       [8.76],
       [9.02],
       [7.68],
       [8.97],
       [8.12],
       [9.18],
       [8.76],
       [8.02],
       [8.  ],
       [9.01],
       [8.68],
       [8.1 ],
       [8.45],
       [8.79],
       [8.47],
       [7.

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
lm=LinearRegression()

In [18]:
lm.fit(x_train,y_train)

LinearRegression()

In [19]:
Ypredict=lm.predict(x_test)

In [20]:
Ypredict

array([[0.71526369],
       [0.72367342],
       [0.75731236],
       [0.65219067],
       [0.75100506],
       [0.61855173],
       [0.74259533],
       [0.61644929],
       [0.8834584 ],
       [0.896073  ],
       [0.55547871],
       [0.86663893],
       [0.71526369],
       [0.43984484],
       [0.82879512],
       [0.6606004 ],
       [0.6353712 ],
       [0.83930729],
       [0.57440061],
       [0.74259533],
       [0.84140972],
       [0.83720485],
       [0.69634178],
       [0.45876675],
       [0.78043914],
       [0.60593712],
       [0.50081543],
       [0.6606004 ],
       [0.84771702],
       [0.65008823],
       [0.60593712],
       [0.71316125],
       [0.73418559],
       [0.60383469],
       [0.79095131],
       [0.74890263],
       [0.58070792],
       [0.85612676],
       [0.6542931 ],
       [0.94653142],
       [0.69423935],
       [0.6542931 ],
       [0.63957607],
       [0.78043914],
       [0.83089755],
       [0.59752739],
       [0.5239422 ],
       [0.675

In [21]:
comparison=pd.DataFrame(x_test,columns=["input Data"])

In [22]:
comparison["AVL_o/p"]=y_test

In [23]:
comparison

input Data  AVL_o/p
0         8.56     0.71
1         8.60     0.70
2         8.76     0.79
3         8.26     0.73
4         8.73     0.72
..         ...      ...
75        8.20     0.61
76        8.36     0.69
77        8.43     0.62
78        9.54     0.93
79        7.89     0.43

[80 rows x 2 columns]

In [24]:
comparison["Pred_o/p"]=Ypredict

In [25]:
comparison

input Data  AVL_o/p  Pred_o/p
0         8.56     0.71  0.715264
1         8.60     0.70  0.723673
2         8.76     0.79  0.757312
3         8.26     0.73  0.652191
4         8.73     0.72  0.751005
..         ...      ...       ...
75        8.20     0.61  0.639576
76        8.36     0.69  0.673215
77        8.43     0.62  0.687932
78        9.54     0.93  0.921302
79        7.89     0.43  0.574401

[80 rows x 3 columns]

# MULTIPLE LINEAR REGRESSION

In [26]:
my_data

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

    Research  Chance of Admit   
0        Yes              0.92  
1        Yes              0.76  
2        Yes              0.72  
3        Yes              0.80  
4         No              0.65  
..       ...               ...  
395      Yes              0.82  
396      Yes              0.84  
397      Yes              0.91  
398       No              0.67  
399      Yes              0.95  

[400 rows x 9 columns]

In [75]:
X1=my_data.iloc[:,1:6].values

In [77]:
X1

array([[337. , 118. ,   4. ,   4.5,   4.5],
       [324. , 107. ,   4. ,   4. ,   4.5],
       [316. , 104. ,   3. ,   3. ,   3.5],
       ...,
       [330. , 116. ,   4. ,   5. ,   4.5],
       [312. , 103. ,   3. ,   3.5,   4. ],
       [333. , 117. ,   4. ,   5. ,   4. ]])

In [78]:
Y1=my_data.iloc[:,8].values

In [79]:
Y1

array([0.92, 0.76, 0.72, 0.8 , 0.65, 0.9 , 0.75, 0.68, 0.5 , 0.45, 0.52,
       0.84, 0.78, 0.62, 0.61, 0.54, 0.66, 0.65, 0.63, 0.62, 0.64, 0.7 ,
       0.94, 0.95, 0.97, 0.94, 0.76, 0.44, 0.46, 0.54, 0.65, 0.74, 0.91,
       0.9 , 0.94, 0.88, 0.64, 0.58, 0.52, 0.48, 0.46, 0.49, 0.53, 0.87,
       0.91, 0.88, 0.86, 0.89, 0.82, 0.78, 0.76, 0.56, 0.78, 0.72, 0.7 ,
       0.64, 0.64, 0.46, 0.36, 0.42, 0.48, 0.47, 0.54, 0.56, 0.52, 0.55,
       0.61, 0.57, 0.68, 0.78, 0.94, 0.96, 0.93, 0.84, 0.74, 0.72, 0.74,
       0.64, 0.44, 0.46, 0.5 , 0.96, 0.92, 0.92, 0.94, 0.76, 0.72, 0.66,
       0.64, 0.74, 0.64, 0.38, 0.34, 0.44, 0.36, 0.42, 0.48, 0.86, 0.9 ,
       0.79, 0.71, 0.64, 0.62, 0.57, 0.74, 0.69, 0.87, 0.91, 0.93, 0.68,
       0.61, 0.69, 0.62, 0.72, 0.59, 0.66, 0.56, 0.45, 0.47, 0.71, 0.94,
       0.94, 0.57, 0.61, 0.57, 0.64, 0.85, 0.78, 0.84, 0.92, 0.96, 0.77,
       0.71, 0.79, 0.89, 0.82, 0.76, 0.71, 0.8 , 0.78, 0.84, 0.9 , 0.92,
       0.97, 0.8 , 0.81, 0.75, 0.83, 0.96, 0.79, 0.

In [81]:
X1_train,X1_test,Y1_train,Y1_test=train_test_split(X1,Y1,test_size=0.2,random_state=0)

In [83]:
X1_test

array([[309. , 105. ,   5. ,   3.5,   3.5],
       [308. , 110. ,   4. ,   3.5,   3. ],
       [326. , 110. ,   3. ,   3.5,   3.5],
       [306. , 105. ,   2. ,   3. ,   2.5],
       [316. , 105. ,   3. ,   3. ,   3.5],
       [309. , 100. ,   2. ,   3. ,   3. ],
       [312. , 109. ,   3. ,   3. ,   3. ],
       [312. , 104. ,   3. ,   3.5,   4. ],
       [332. , 118. ,   2. ,   4.5,   3.5],
       [331. , 117. ,   4. ,   4.5,   5. ],
       [300. , 105. ,   1. ,   1. ,   2. ],
       [333. , 113. ,   5. ,   4. ,   4. ],
       [320. , 110. ,   2. ,   4. ,   3.5],
       [302. ,  99. ,   1. ,   2. ,   2. ],
       [328. , 112. ,   4. ,   4. ,   4.5],
       [311. , 104. ,   2. ,   2. ,   2. ],
       [312. ,  98. ,   1. ,   3.5,   3. ],
       [329. , 110. ,   2. ,   4. ,   3. ],
       [315. ,  99. ,   2. ,   3.5,   3. ],
       [313. , 107. ,   3. ,   4. ,   4.5],
       [329. , 119. ,   4. ,   4.5,   4.5],
       [327. , 113. ,   4. ,   4.5,   5. ],
       [301. , 106. ,   4. ,   2

In [84]:
lm1=LinearRegression()

In [85]:
lm1.fit(X1,Y1)

LinearRegression()

In [86]:
Y2predict=lm1.predict(X1_test)

In [87]:
Y2predict

array([0.7045427 , 0.69847959, 0.78266586, 0.61023638, 0.70416462,
       0.61075778, 0.69308747, 0.69977594, 0.84926648, 0.91862533,
       0.53957421, 0.88167184, 0.74365143, 0.51857754, 0.85512597,
       0.6042189 , 0.60072002, 0.76776025, 0.63503139, 0.74216378,
       0.90465053, 0.87640228, 0.636686  , 0.48038996, 0.7819061 ,
       0.59193373, 0.48780633, 0.66426788, 0.92829877, 0.69232144,
       0.64433785, 0.75099857, 0.7383416 , 0.52573286, 0.80476562,
       0.77939642, 0.72740776, 0.8383609 , 0.62830408, 0.89694247,
       0.7464451 , 0.70633097, 0.76781358, 0.80690063, 0.85206785,
       0.76149691, 0.6453075 , 0.74749848, 0.61032855, 0.60190779,
       0.65779125, 0.77251324, 0.61193445, 0.92710691, 0.68912802,
       0.72303378, 0.85583866, 0.77097566, 0.79365712, 0.81948691,
       0.75167726, 0.43831311, 0.64562188, 0.54115647, 0.85187512,
       0.75668648, 0.71609318, 0.84922621, 0.76770621, 0.71637622,
       0.64595146, 0.81337726, 0.75710822, 0.64733802, 0.92771

In [89]:
comparison=pd.DataFrame(X1_test,columns=["input data","1","2","3","4"])

In [90]:
comparison

input data      1    2    3    4
0        309.0  105.0  5.0  3.5  3.5
1        308.0  110.0  4.0  3.5  3.0
2        326.0  110.0  3.0  3.5  3.5
3        306.0  105.0  2.0  3.0  2.5
4        316.0  105.0  3.0  3.0  3.5
..         ...    ...  ...  ...  ...
75       311.0  104.0  3.0  3.5  2.0
76       306.0  103.0  2.0  2.5  3.0
77       313.0  106.0  2.0  2.5  2.0
78       334.0  116.0  4.0  4.0  3.5
79       297.0   96.0  2.0  2.5  1.5

[80 rows x 5 columns]

In [91]:
comparison["AVL_o/p"]=Y1_test

In [92]:
comparison

input data      1    2    3    4  AVL_o/p
0        309.0  105.0  5.0  3.5  3.5     0.71
1        308.0  110.0  4.0  3.5  3.0     0.70
2        326.0  110.0  3.0  3.5  3.5     0.79
3        306.0  105.0  2.0  3.0  2.5     0.73
4        316.0  105.0  3.0  3.0  3.5     0.72
..         ...    ...  ...  ...  ...      ...
75       311.0  104.0  3.0  3.5  2.0     0.61
76       306.0  103.0  2.0  2.5  3.0     0.69
77       313.0  106.0  2.0  2.5  2.0     0.62
78       334.0  116.0  4.0  4.0  3.5     0.93
79       297.0   96.0  2.0  2.5  1.5     0.43

[80 rows x 6 columns]

In [93]:
comparison["Pred_o/p"]=Y2predict

In [94]:
comparison

input data      1    2    3    4  AVL_o/p  Pred_o/p
0        309.0  105.0  5.0  3.5  3.5     0.71  0.704543
1        308.0  110.0  4.0  3.5  3.0     0.70  0.698480
2        326.0  110.0  3.0  3.5  3.5     0.79  0.782666
3        306.0  105.0  2.0  3.0  2.5     0.73  0.610236
4        316.0  105.0  3.0  3.0  3.5     0.72  0.704165
..         ...    ...  ...  ...  ...      ...       ...
75       311.0  104.0  3.0  3.5  2.0     0.61  0.627733
76       306.0  103.0  2.0  2.5  3.0     0.69  0.612149
77       313.0  106.0  2.0  2.5  2.0     0.62  0.628285
78       334.0  116.0  4.0  4.0  3.5     0.93  0.872711
79       297.0   96.0  2.0  2.5  1.5     0.43  0.478535

[80 rows x 7 columns]